version: '3.7'

networks:
  overlay-net:
          external: true      
          driver: overlay

services:

  rs:
    image: iudx/rs-depl:latest
    environment:
      - RS_URL=https://rs.iudx.io
      - LOG_LEVEL=INFO
      - RS_JAVA_OPTS=-Xmx4096m
    volumes:
      - ./configs/config-depl.json:/usr/share/app/configs/config.json
      - ./docs/:/usr/share/app/docs
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
    ports:
      - "80:80"
      - "9000:9000"
    restart: on-failure
    networks: 
      - overlay-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "exec java $$RS_JAVA_OPTS  -jar  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory  ./fatjar.jar  --host $$(hostname) -c configs/config.json"

  dev:
    image: iudx/rs-dev:latest
    environment:
      - RS_URL=https://rs.iudx.org.in
      - LOG_LEVEL=INFO
    volumes:
      - ./configs/config-dev.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - ./docs/:/usr/share/app/docs
    ports:
      - "8080:80"
      - "9000:9000"
    restart: on-failure
    networks: 
      - overlay-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "exec java -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"

  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - overlay-net
